package br.com.HEALTHTRACK.API.HEALTHTRACK.Enum.SintomaEnum;

public enum TipoSintoma {
    FISICO,
    PSICOLOGICO,
    NEUROLOGICO,
    GASTROINTESTINAL,
    RESPIRATORIO,
    CARDIOVASCULAR,
    DERMATOLOGICO,
    MUSCULOESQUELETICO,
    SENSORIAL,
    GENERALIZADO
}
